### ISSUE TITLE
kong-httpbin template does not work with `gwa apply`

### ISSUE THREAD

**Issue by rustyjux** [bcgov/gwa-cli#105]
Need to add `kind: GatewayService` and remove one level of indentation.

That is, turn:
```
services:
  - name: testabc199-dev
    tags: [ ns.gw-abc123 ]
    host: httpbin.org
    port: 443
    protocol: https
    retries: 0
    routes:
      - name: testabc199-dev
        tags: [ ns.gw-abc123 ]
        hosts:
        - testabc19.dev.api.gov.bc.ca
        paths:
        - /
        methods:
        - GET
        strip_path: true
        https_redirect_status_code: 426
        path_handling: v0
        request_buffering: true
        response_buffering: true
```

into:

```
kind: GatewayService
name: testabc199-dev
tags: [ ns.gw-abc123 ]
host: httpbin.org
port: 443
protocol: https
retries: 0
routes:
  - name: testabc199-dev
    tags: [ ns.gw-abc123 ]
    hosts:
    - testabc19.dev.api.gov.bc.ca
    paths:
    - /
    methods:
    - GET
    strip_path: true
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
```
