### ISSUE TITLE
Namespace to Gateway - Create minimal `basic-service` template for Gateways Get Started

### ISSUE THREAD

**Issue by rustyjux** [bcgov/gwa-cli#109]
Create an ultra simplistic gw-config template for a users first time using the Portal. 

Should:
- be compatible with `gwa apply`

Something like this:
```
services:
 - url: https://httpbin.org
   tags: [ ns.gw-abc123 ]
   name: rjv-example-service
   routes:
     - hosts: 
         - rjv-example-service.api.gov.bc.ca
       name: base
       tags: [ ns.gw-abc123 ]
```

Should also:
- include a Product, ProductEnvironment, DraftDataset - draft dataset should use the template for API Directory listings (https://dpdd.atlassian.net/issues/APS-2598)
- use the same conventions as other templates to append `-dev` onto service names
