### ISSUE TITLE
Gateway config are not combined into one document for `apply`

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-cli#72]
The `apply` command takes a file that has one or more resources defined.  For the resource Kind of `GatewayService`, all these resources have to be combined into one document before sending to the `/gw/api` endpoint.

For example:

```yaml
kind: GatewayService
name: service-1
host: api.co1.com
---
kind: GatewayService
name: service-2
host: api.co2.com
---
kind: GatewayService
name: service-3
host: api.co3.com
```

Needs to be sent as:

```yaml
services:
- name: service-1
  host: api.co1.com
- name: service-2
  host: api.co2.com
- name: service-3
  host: api.co3.com
```
